services:
  - type: web
    name: hijrahgizi-py-service
    runtime: python
    plan: free
    rootDir: py-service
    healthCheckPath: /health
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT